# Generated by Django 4.2 on 2025-12-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seem',
            new_name='seen',
        ),
    ]
